gr_gameficator:
    resource: "@GRGameficatorBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@GRUserBundle/Resources/config/routing/all.xml"
