<?php

namespace GR\GameficatorBundle\Repository;

/**
 * ListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListRepository extends \Doctrine\ORM\EntityRepository
{
}
