<?php

namespace GR\GameficatorBundle\Repository;

/**
 * RecurrentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecurrentRepository extends \Doctrine\ORM\EntityRepository
{
}
