gr_gameficator_homepage:
    path:     /
    defaults: { _controller: GRGameficatorBundle:Gameficator:index }


gr_gameficator_createtask:
    path:     /createTask
    defaults: { _controller: GRGameficatorBundle:Gameficator:createTask }

gr_gameficator_taskstodo:
    path:     /tasksToDo
    defaults: { _controller: GRGameficatorBundle:Gameficator:tasksToDo }

gr_gameficator_tachesarchivees:
    path:     /tachesArchivees
    defaults: { _controller: GRGameficatorBundle:Gameficator:tachesArchivees }

gr_gameficator_tachescorbeille:
    path:     /tachesCorbeille
    defaults: { _controller: GRGameficatorBundle:Gameficator:tachesCorbeille }

gr_gameficator_createproject:
    path:    /createProject
    defaults: {_controller: GRGameficatorBundle:Gameficator:createProject }

gr_gameficator_createreward:
    path:    /createReward
    defaults: {_controller: GRGameficatorBundle:Gameficator:createReward }

gr_gameficator_createtopic:
    path:    /createTopic
    defaults: {_controller: GRGameficatorBundle:Gameficator:createTopic }

gr_gameficator_updatetask:
    path:    /updateTask/{id}
    defaults: {_controller: GRGameficatorBundle:Gameficator:updateTask }

gr_gameficator_updateproject:
    path:    /updateProject/{id}
    defaults: {_controller: GRGameficatorBundle:Gameficator:updateProject }

gr_gameficator_updatereward:
    path:    /updateReward/{id}
    defaults: {_controller: GRGameficatorBundle:Gameficator:updateReward }

gr_gameficator_viewprojects:
    path:    /mesProjets
    defaults: {_controller: GRGameficatorBundle:Gameficator:viewProjects }

gr_gameficator_viewrewards:
    path:    /mesRécompenses
    defaults: {_controller: GRGameficatorBundle:Gameficator:viewRewards }


gr_gameficator_viewreward:
    path:    /reward/{id}
    defaults: {_controller: GRGameficatorBundle:Gameficator:viewReward }

gr_gameficator_viewproject:
    path:    /project/{id}
    defaults: {_controller: GRGameficatorBundle:Gameficator:viewProject }

gr_gameficator_viewtask:
    path:    /task/{id}
    defaults: {_controller: GRGameficatorBundle:Gameficator:viewTask }
