gr_gameficator_homepage:
    path:     /
    defaults: { _controller: GRGameficatorBundle:Gameficator:index }

gr_gameficator_createtask:
    path:     /createTask
    defaults: { _controller: GRGameficatorBundle:Gameficator:createTask }

gr_gameficator_taskstodo:
    path:     /tasksToDo
    defaults: { _controller: GRGameficatorBundle:Gameficator:tasksToDo }

gr_gameficator_createproject:
    path:    /createProject
    defaults: {_controller: GRGameficatorBundle:Gameficator:createProject }

gr_gameficator_createreward:
    path:    /createReward
    defaults: {_controller: GRGameficatorBundle:Gameficator:createReward }

gr_gameficator_viewprojects:
    path:    /mesProjets
    defaults: {_controller: GRGameficatorBundle:Gameficator:viewProjects }

gr_gameficator_viewrewards:
    path:    /mesRécompenses
    defaults: {_controller: GRGameficatorBundle:Gameficator:viewRewards }

gr_gameficator_viewreward:
    path:    /reward/{id}
    defaults: {_controller: GRGameficatorBundle:Gameficator:viewReward }

gr_gameficator_viewproject:
    path:    /project/{id}
    defaults: {_controller: GRGameficatorBundle:Gameficator:viewProject }

gr_gameficator_viewtask:
    path:    /task/{id}
    defaults: {_controller: GRGameficatorBundle:Gameficator:viewTask }