gr_gameficator_homepage:
    path:     /
    defaults: { _controller: GRGameficatorBundle:Gameficator:index }

gr_gameficator_createtask:
    path:     /createTask
    defaults: { _controller: GRGameficatorBundle:Gameficator:createTask }

gr_gameficator_taskstodo:
    path:     /tasksToDo
    defaults: { _controller: GRGameficatorBundle:Gameficator:tasksToDo }
